### ISSUE TITLE
add space to cheat sheet

### ISSUE THREAD

**Issue by starchyunderscore** [tmatz/android-unistroke-keyboard#26]
cant figure out how to input a space, maybe im just bad, but i would love if it were added to the "cheat sheet", the big image with all the inputs.

**Comment by tmatz** [comment]
@starchyunderscore 
Thank you for pointing it out!

I had missed adding 'space' in the cheat sheet. I'll add it now. 

The gesture for 'space' is a horizontal line pointing to the right (opposite of 'BS').
